import type { AdConfigEntry, AdPlacement } from '@/types/ads';

export const AD_CONFIG: Record<AdPlacement, AdConfigEntry> = {
  home_top_leaderboard: {
    slot: '1234567890',
    network: 'adSense',
    format: 'horizontal',
    responsive: true,
    label: 'Home top leaderboard',
    breakpoints: {
      mobile: { width: '100%', height: 90 },
      tablet: { width: '728px', height: 90 },
      desktop: { width: '970px', height: 90 },
    },
  },
  home_mid_rectangle: {
    slot: '1234567891',
    network: 'adSense',
    format: 'rectangle',
    responsive: true,
    label: 'Home mid rectangle',
    breakpoints: {
      mobile: { width: '100%', height: 250 },
      tablet: { width: '728px', height: 250 },
      desktop: { width: '728px', height: 250 },
    },
  },
  home_bottom_multiplex: {
    slot: '1234567892',
    network: 'adSense',
    format: 'horizontal',
    responsive: true,
    label: 'Home bottom multiplex',
    breakpoints: {
      mobile: { width: '100%', height: 90 },
      tablet: { width: '728px', height: 90 },
      desktop: { width: '970px', height: 90 },
    },
  },
  tool_top_banner: {
    slot: '2234567890',
    network: 'adSense',
    format: 'horizontal',
    responsive: true,
    label: 'Tool top banner',
    breakpoints: {
      mobile: { width: '100%', height: 90 },
      tablet: { width: '728px', height: 90 },
      desktop: { width: '970px', height: 90 },
    },
  },
  tool_after_tool: {
    slot: '2234567891',
    network: 'adSense',
    format: 'rectangle',
    responsive: true,
    label: 'Tool after interaction',
    breakpoints: {
      mobile: { width: '100%', height: 250 },
      tablet: { width: '728px', height: 250 },
      desktop: { width: '728px', height: 250 },
    },
  },
  tool_bottom_content: {
    slot: '2234567892',
    network: 'adSense',
    format: 'horizontal',
    responsive: true,
    label: 'Tool content footer',
    breakpoints: {
      mobile: { width: '100%', height: 90 },
      tablet: { width: '728px', height: 90 },
      desktop: { width: '970px', height: 90 },
    },
  },
  tool_sidebar: {
    slot: '2234567893',
    network: 'adSense',
    format: 'vertical',
    responsive: true,
    label: 'Tool sidebar',
    breakpoints: {
      mobile: { width: '0px', height: 0 },
      tablet: { width: '300px', height: 600 },
      desktop: { width: '300px', height: 600 },
    },
  },
  mobile_sticky_anchor: {
    slot: '2234567894',
    network: 'adSense',
    format: 'horizontal',
    responsive: true,
    label: 'Mobile sticky anchor',
    breakpoints: {
      mobile: { width: '100%', height: 90 },
      tablet: { width: '100%', height: 90 },
      desktop: { width: '0px', height: 0 },
    },
  },
  blog_top_leaderboard: {
    slot: '3234567890',
    network: 'adSense',
    format: 'horizontal',
    responsive: true,
    label: 'Blog top leaderboard',
    breakpoints: {
      mobile: { width: '100%', height: 90 },
      tablet: { width: '728px', height: 90 },
      desktop: { width: '970px', height: 90 },
    },
  },
  blog_inline_rectangle: {
    slot: '3234567891',
    network: 'adSense',
    format: 'rectangle',
    responsive: true,
    label: 'Blog inline rectangle',
    breakpoints: {
      mobile: { width: '100%', height: 250 },
      tablet: { width: '728px', height: 250 },
      desktop: { width: '728px', height: 250 },
    },
  },
  blog_paragraph: {
    slot: '3234567892',
    network: 'adSense',
    format: 'rectangle',
    responsive: true,
    label: 'Blog paragraph ad',
    breakpoints: {
      mobile: { width: '100%', height: 250 },
      tablet: { width: '728px', height: 250 },
      desktop: { width: '728px', height: 250 },
    },
  },
  blog_sidebar: {
    slot: '3234567893',
    network: 'adSense',
    format: 'vertical',
    responsive: true,
    label: 'Blog sidebar',
    breakpoints: {
      mobile: { width: '0px', height: 0 },
      tablet: { width: '300px', height: 600 },
      desktop: { width: '300px', height: 600 },
    },
  },
  blog_bottom_multiplex: {
    slot: '3234567894',
    network: 'adSense',
    format: 'horizontal',
    responsive: true,
    label: 'Blog bottom multiplex',
    breakpoints: {
      mobile: { width: '100%', height: 90 },
      tablet: { width: '728px', height: 90 },
      desktop: { width: '970px', height: 90 },
    },
  },
  category_top_leaderboard: {
    slot: '4234567890',
    network: 'adSense',
    format: 'horizontal',
    responsive: true,
    label: 'Category top leaderboard',
    breakpoints: {
      mobile: { width: '100%', height: 90 },
      tablet: { width: '728px', height: 90 },
      desktop: { width: '970px', height: 90 },
    },
  },
  category_grid_rectangle: {
    slot: '4234567891',
    network: 'adSense',
    format: 'rectangle',
    responsive: true,
    label: 'Category grid rectangle',
    breakpoints: {
      mobile: { width: '100%', height: 250 },
      tablet: { width: '728px', height: 250 },
      desktop: { width: '728px', height: 250 },
    },
  },
  category_sidebar: {
    slot: '4234567892',
    network: 'adSense',
    format: 'vertical',
    responsive: true,
    label: 'Category sidebar',
    breakpoints: {
      mobile: { width: '0px', height: 0 },
      tablet: { width: '300px', height: 600 },
      desktop: { width: '300px', height: 600 },
    },
  },
  multiplex_leaderboard: {
    slot: '5234567890',
    network: 'adSense',
    format: 'horizontal',
    responsive: true,
    label: 'Multiplex leaderboard',
    breakpoints: {
      mobile: { width: '100%', height: 90 },
      tablet: { width: '728px', height: 90 },
      desktop: { width: '970px', height: 90 },
    },
  },
  multiplex_rectangle: {
    slot: '5234567891',
    network: 'adSense',
    format: 'rectangle',
    responsive: true,
    label: 'Multiplex rectangle',
    breakpoints: {
      mobile: { width: '100%', height: 250 },
      tablet: { width: '728px', height: 250 },
      desktop: { width: '728px', height: 250 },
    },
  },
};
